/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    darkMode: 'class', // Habilita o modo escuro via classe
    theme: {
        extend: {
            colors: {
                // Cores customizadas para os temas
                primary: {
                    50: 'rgb(var(--color-primary-50) / <alpha-value>)',
                    100: 'rgb(var(--color-primary-100) / <alpha-value>)',
                    200: 'rgb(var(--color-primary-200) / <alpha-value>)',
                    300: 'rgb(var(--color-primary-300) / <alpha-value>)',
                    400: 'rgb(var(--color-primary-400) / <alpha-value>)',
                    500: 'rgb(var(--color-primary-500) / <alpha-value>)',
                    600: 'rgb(var(--color-primary-600) / <alpha-value>)',
                    700: 'rgb(var(--color-primary-700) / <alpha-value>)',
                    800: 'rgb(var(--color-primary-800) / <alpha-value>)',
                    900: 'rgb(var(--color-primary-900) / <alpha-value>)',
                    950: 'rgb(var(--color-primary-950) / <alpha-value>)',
                },
                secondary: {
                    50: 'rgb(var(--color-secondary-50) / <alpha-value>)',
                    100: 'rgb(var(--color-secondary-100) / <alpha-value>)',
                    200: 'rgb(var(--color-secondary-200) / <alpha-value>)',
                    300: 'rgb(var(--color-secondary-300) / <alpha-value>)',
                    400: 'rgb(var(--color-secondary-400) / <alpha-value>)',
                    500: 'rgb(var(--color-secondary-500) / <alpha-value>)',
                    600: 'rgb(var(--color-secondary-600) / <alpha-value>)',
                    700: 'rgb(var(--color-secondary-700) / <alpha-value>)',
                    800: 'rgb(var(--color-secondary-800) / <alpha-value>)',
                    900: 'rgb(var(--color-secondary-900) / <alpha-value>)',
                    950: 'rgb(var(--color-secondary-950) / <alpha-value>)',
                },
                success: {
                    50: 'rgb(var(--color-success-50) / <alpha-value>)',
                    100: 'rgb(var(--color-success-100) / <alpha-value>)',
                    200: 'rgb(var(--color-success-200) / <alpha-value>)',
                    300: 'rgb(var(--color-success-300) / <alpha-value>)',
                    400: 'rgb(var(--color-success-400) / <alpha-value>)',
                    500: 'rgb(var(--color-success-500) / <alpha-value>)',
                    600: 'rgb(var(--color-success-600) / <alpha-value>)',
                    700: 'rgb(var(--color-success-700) / <alpha-value>)',
                    800: 'rgb(var(--color-success-800) / <alpha-value>)',
                    900: 'rgb(var(--color-success-900) / <alpha-value>)',
                    950: 'rgb(var(--color-success-950) / <alpha-value>)',
                },
                warning: {
                    50: 'rgb(var(--color-warning-50) / <alpha-value>)',
                    100: 'rgb(var(--color-warning-100) / <alpha-value>)',
                    200: 'rgb(var(--color-warning-200) / <alpha-value>)',
                    300: 'rgb(var(--color-warning-300) / <alpha-value>)',
                    400: 'rgb(var(--color-warning-400) / <alpha-value>)',
                    500: 'rgb(var(--color-warning-500) / <alpha-value>)',
                    600: 'rgb(var(--color-warning-600) / <alpha-value>)',
                    700: 'rgb(var(--color-warning-700) / <alpha-value>)',
                    800: 'rgb(var(--color-warning-800) / <alpha-value>)',
                    900: 'rgb(var(--color-warning-900) / <alpha-value>)',
                    950: 'rgb(var(--color-warning-950) / <alpha-value>)',
                },
                background: 'rgb(var(--color-background) / <alpha-value>)',
                foreground: 'rgb(var(--color-foreground) / <alpha-value>)',
                card: 'rgb(var(--color-card) / <alpha-value>)',
                'card-foreground': 'rgb(var(--color-card-foreground) / <alpha-value>)',
                'card-elevated': 'rgb(var(--color-card-elevated) / <alpha-value>)',
                popover: 'rgb(var(--color-popover) / <alpha-value>)',
                'popover-foreground': 'rgb(var(--color-popover-foreground) / <alpha-value>)',
                muted: 'rgb(var(--color-muted) / <alpha-value>)',
                'muted-foreground': 'rgb(var(--color-muted-foreground) / <alpha-value>)',
                accent: 'rgb(var(--color-accent) / <alpha-value>)',
                'accent-foreground': 'rgb(var(--color-accent-foreground) / <alpha-value>)',
                destructive: 'rgb(var(--color-destructive) / <alpha-value>)',
                'destructive-foreground': 'rgb(var(--color-destructive-foreground) / <alpha-value>)',
                border: 'rgb(var(--color-border) / <alpha-value>)',
                input: 'rgb(var(--color-input) / <alpha-value>)',
                ring: 'rgb(var(--color-ring) / <alpha-value>)',

                // Cores de indicadores específicas
                'indicator-green': 'rgb(var(--color-indicator-green) / <alpha-value>)',
                'indicator-red': 'rgb(var(--color-indicator-red) / <alpha-value>)',
                'indicator-blue': 'rgb(var(--color-indicator-blue) / <alpha-value>)',
                'indicator-yellow': 'rgb(var(--color-indicator-yellow) / <alpha-value>)',

                // Cores neon específicas do Dashfolio Plus
                'neon-green': 'rgb(0 255 136 / <alpha-value>)',
                'neon-blue': 'rgb(0 191 255 / <alpha-value>)',
                'neon-pink': 'rgb(255 51 102 / <alpha-value>)',
                'neon-yellow': 'rgb(255 220 0 / <alpha-value>)',
                'neon-orange': 'rgb(255 136 0 / <alpha-value>)',
                'neon-purple': 'rgb(147 51 234 / <alpha-value>)',

                // Cores Dashfolio Plus - Esquema Roxo/Violeta
                'dashfolio-purple-light': 'rgb(var(--dashfolio-purple-light) / <alpha-value>)',
                'dashfolio-purple': 'rgb(var(--dashfolio-purple) / <alpha-value>)',
                'dashfolio-purple-dark': 'rgb(var(--dashfolio-purple-dark) / <alpha-value>)',
                'dashfolio-violet': 'rgb(var(--dashfolio-violet) / <alpha-value>)',
                'dashfolio-violet-dark': 'rgb(var(--dashfolio-violet-dark) / <alpha-value>)',
                'dashfolio-blue-light': 'rgb(var(--dashfolio-blue-light) / <alpha-value>)',
                'dashfolio-blue': 'rgb(var(--dashfolio-blue) / <alpha-value>)',
                'dashfolio-indigo': 'rgb(var(--dashfolio-indigo) / <alpha-value>)',
                'dashfolio-cyan': 'rgb(var(--dashfolio-cyan) / <alpha-value>)',

                // Cores Sofisticadas - Palette Premium
                'outer-space': {
                    100: 'rgb(var(--outer-space-100) / <alpha-value>)',
                    200: 'rgb(var(--outer-space-200) / <alpha-value>)',
                    300: 'rgb(var(--outer-space-300) / <alpha-value>)',
                    400: 'rgb(var(--outer-space-400) / <alpha-value>)',
                    DEFAULT: 'rgb(var(--outer-space-500) / <alpha-value>)',
                    500: 'rgb(var(--outer-space-500) / <alpha-value>)',
                    600: 'rgb(var(--outer-space-600) / <alpha-value>)',
                    700: 'rgb(var(--outer-space-700) / <alpha-value>)',
                    800: 'rgb(var(--outer-space-800) / <alpha-value>)',
                    900: 'rgb(var(--outer-space-900) / <alpha-value>)',
                },
                'night': {
                    100: 'rgb(var(--night-100) / <alpha-value>)',
                    200: 'rgb(var(--night-200) / <alpha-value>)',
                    300: 'rgb(var(--night-300) / <alpha-value>)',
                    400: 'rgb(var(--night-400) / <alpha-value>)',
                    DEFAULT: 'rgb(var(--night-500) / <alpha-value>)',
                    500: 'rgb(var(--night-500) / <alpha-value>)',
                    600: 'rgb(var(--night-600) / <alpha-value>)',
                    700: 'rgb(var(--night-700) / <alpha-value>)',
                    800: 'rgb(var(--night-800) / <alpha-value>)',
                    900: 'rgb(var(--night-900) / <alpha-value>)',
                },
                'licorice': {
                    100: 'rgb(var(--licorice-100) / <alpha-value>)',
                    200: 'rgb(var(--licorice-200) / <alpha-value>)',
                    300: 'rgb(var(--licorice-300) / <alpha-value>)',
                    400: 'rgb(var(--licorice-400) / <alpha-value>)',
                    DEFAULT: 'rgb(var(--licorice-500) / <alpha-value>)',
                    500: 'rgb(var(--licorice-500) / <alpha-value>)',
                    600: 'rgb(var(--licorice-600) / <alpha-value>)',
                    700: 'rgb(var(--licorice-700) / <alpha-value>)',
                    800: 'rgb(var(--licorice-800) / <alpha-value>)',
                    900: 'rgb(var(--licorice-900) / <alpha-value>)',
                },
                'caput-mortuum': {
                    100: 'rgb(var(--caput-mortuum-100) / <alpha-value>)',
                    200: 'rgb(var(--caput-mortuum-200) / <alpha-value>)',
                    300: 'rgb(var(--caput-mortuum-300) / <alpha-value>)',
                    400: 'rgb(var(--caput-mortuum-400) / <alpha-value>)',
                    DEFAULT: 'rgb(var(--caput-mortuum-500) / <alpha-value>)',
                    500: 'rgb(var(--caput-mortuum-500) / <alpha-value>)',
                    600: 'rgb(var(--caput-mortuum-600) / <alpha-value>)',
                    700: 'rgb(var(--caput-mortuum-700) / <alpha-value>)',
                    800: 'rgb(var(--caput-mortuum-800) / <alpha-value>)',
                    900: 'rgb(var(--caput-mortuum-900) / <alpha-value>)',
                },
                'eerie-black': {
                    100: 'rgb(var(--eerie-black-100) / <alpha-value>)',
                    200: 'rgb(var(--eerie-black-200) / <alpha-value>)',
                    300: 'rgb(var(--eerie-black-300) / <alpha-value>)',
                    400: 'rgb(var(--eerie-black-400) / <alpha-value>)',
                    DEFAULT: 'rgb(var(--eerie-black-500) / <alpha-value>)',
                    500: 'rgb(var(--eerie-black-500) / <alpha-value>)',
                    600: 'rgb(var(--eerie-black-600) / <alpha-value>)',
                    700: 'rgb(var(--eerie-black-700) / <alpha-value>)',
                    800: 'rgb(var(--eerie-black-800) / <alpha-value>)',
                    900: 'rgb(var(--eerie-black-900) / <alpha-value>)',
                },
                'raisin-black': {
                    100: 'rgb(var(--raisin-black-100) / <alpha-value>)',
                    200: 'rgb(var(--raisin-black-200) / <alpha-value>)',
                    300: 'rgb(var(--raisin-black-300) / <alpha-value>)',
                    400: 'rgb(var(--raisin-black-400) / <alpha-value>)',
                    DEFAULT: 'rgb(var(--raisin-black-500) / <alpha-value>)',
                    500: 'rgb(var(--raisin-black-500) / <alpha-value>)',
                    600: 'rgb(var(--raisin-black-600) / <alpha-value>)',
                    700: 'rgb(var(--raisin-black-700) / <alpha-value>)',
                    800: 'rgb(var(--raisin-black-800) / <alpha-value>)',
                    900: 'rgb(var(--raisin-black-900) / <alpha-value>)',
                },

                // Cores específicas do sistema original Telescope
                'telescope-dark': '#222233',
                'telescope-card': '#1b202d',
                'telescope-gradient-start': 'rgba(2,0,36,1)',
                'telescope-gradient-mid': 'rgba(101,9,121,1)',
                'telescope-gradient-end': 'rgba(51,4,66,1)',
                'telescope-icon': '#d1d4d4',
                'telescope-text': '#525f7f',
            },
            backgroundImage: {
                'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
                'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',

                // Gradientes específicos do sistema original
                'telescope-header': 'linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(101,9,121,1) 35%, rgba(51,4,66,1) 100%)',
                'telescope-card': 'linear-gradient(135deg, rgba(0,0,0,0.59) 0%, rgba(27,32,45,0.938813025210084) 56%, rgba(27,32,45,0.8015581232492998) 100%)',

                // Gradientes Dashfolio Plus
                'dashfolio-primary': 'var(--dashfolio-gradient-primary)',
                'dashfolio-secondary': 'var(--dashfolio-gradient-secondary)',
                'dashfolio-dark': 'var(--dashfolio-gradient-dark)',
                'dashfolio-sidebar': 'linear-gradient(135deg, rgb(30 27 75) 0%, rgb(15 23 42) 100%)',
                'dashfolio-glow': 'linear-gradient(135deg, rgba(124 58 237 / 0.3) 0%, rgba(59 130 246 / 0.3) 100%)',

                // Gradiente Sofisticado do Novo Tema
                'sidebar-sophisticated': 'var(--sidebar-gradient)',
            },
            boxShadow: {
                'theme': 'var(--shadow-theme)',
                'theme-lg': 'var(--shadow-theme-lg)',
                'theme-xl': 'var(--shadow-theme-xl)',
                'neon': 'var(--shadow-neon)',
                'neon-green': '0 0 20px rgb(0 255 136 / 0.3)',
                'neon-blue': '0 0 20px rgb(0 191 255 / 0.3)',
                'neon-pink': '0 0 20px rgb(255 51 102 / 0.3)',
                'neon-yellow': '0 0 20px rgb(255 220 0 / 0.3)',
                'telescope': '0 8px 32px -8px rgba(0, 0, 0, 0.4), 0 4px 16px -4px rgba(0, 0, 0, 0.3)',

                // Sombras Dashfolio Plus
                'dashfolio': '0 4px 20px -2px rgba(124 58 237 / 0.3)',
                'dashfolio-lg': '0 8px 32px -4px rgba(124 58 237 / 0.4)',
                'dashfolio-purple': '0 0 30px rgba(124 58 237 / 0.5)',
                'dashfolio-blue': '0 0 30px rgba(59 130 246 / 0.5)',
                'dashfolio-glow': '0 0 40px rgba(167 139 250 / 0.6)',
            },
            backdropBlur: {
                'theme': 'var(--backdrop-blur)',
            }
        },
    },
    plugins: [],
}
